spring:
  thymeleaf:
    cache: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/springbootProduct/v3
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB